version: '3'
volumes:
  postgres_data_todo:
    driver: local
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./front-end/nginx.conf:/etc/nginx/nginx.conf
      - ./front-end/otel-nginx.toml:/etc/nginx/otel-nginx.toml
    ports:
      - 3000:80
    depends_on:
      - backend
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env.production
    ports:
      - 5000:80
    depends_on:
      - db
  db:
    container_name: todo_db
    image: postgres
    volumes:
      - postgres_data_todo:/var/lib/postgresql/data
      - ./back-end/db/initdb.d/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass-sword
    ports:
      - 5432:5432